# -*- coding: utf-8 -*-
"""GDP VS FERTILITY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ro-0GtGgaq5IoDwZSTGMW7s81edEuSWo
"""

#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#loading the datasets
df1 = pd.read_csv('/content/fertility_woman.csv',skiprows=4)
df2  = pd.read_csv('/content/gdp_per_capita.csv',skiprows=4)

# checking the structure
df1.head()

df2.head()

df1.tail()

df2.tail()

# checking missing values
df1.isnull().sum()

# checking missing values
df2.isnull().sum()

# Drop columns with missing data
df1 = df1.drop(columns=[str(year) for year in range(1960, 1990)] + ['2023'])
df2 = df2.drop(columns=[str(year) for year in range(1960, 1990)] + ['2023'])

df1.head()

df2.head()

#Drop the Unnamed: 68 column
df1 = df1.drop(columns=['Unnamed: 68'], errors='ignore')
df2= df2.drop(columns=['Unnamed: 68'], errors='ignore')

df1.head()

df2.head()



df1[['Country Name'] + [str(year) for year in range(1990, 2023)]].copy()

df2[['Country Name'] + [str(year) for year in range(1990, 2023)]].copy()

df1_years = df1.loc[:, ['Country Name'] + [str(year) for year in range(1990, 2023)]]
df2_years = df2.loc[:, ['Country Name'] + [str(year) for year in range(1990, 2023)]]

##
df1.iloc[:, 1:] = df1.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')
df2.iloc[:, 1:] = df2.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

# Fill NaNs with the mean for each year column (ignoring "Country Name")
df1.iloc[:, 1:] = df1.iloc[:, 1:].apply(lambda x: x.fillna(x.mean()), axis=0)
df2.iloc[:, 1:] = df2.iloc[:, 1:].apply(lambda x: x.fillna(x.mean()), axis=0)

df1.isnull().sum()

df1.head()

df2.head()

## melting the 2 data frame
# converts  a DataFrame from a wide format (where each year is a separate column) to a long format (where each year becomes a row with associated values).



available_years = [str(year) for year in range(1990, 2023) if str(year) in df1.columns]

# Keep "Country Name" as the identifier
# Specify year columns to melt
# Name of the new column for years
# Name of the new column for values

melted_df1 = pd.melt(df1,id_vars=['Country Name'],value_vars= available_years,var_name='Year',value_name='Fertility Rate')

melted_df1.head()

melted_df2 = pd.melt(df2,id_vars=['Country Name'],value_vars=available_years,var_name='Year',value_name='GDP')

melted_df2.head()

# Merged df1_melted and df2_melted on 'Country Name' and 'Year'
merged_df = pd.merge(melted_df1, melted_df2, on=['Country Name', 'Year'], how='outer', suffixes=('_df1', '_df2'))

merged_df.head()

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=merged_df)

# extracting 2013 data
df_2013 = merged_df[merged_df['Year'] == '2013']

df_2013.head()

numerical_columns = merged_df.select_dtypes(include=['float64', 'int64']).columns

correlation_matrix = merged_df[numerical_columns].corr()

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", cbar=True)
plt.title('Correlation Heatmap for Merged Data')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_2013, x='GDP', y='Fertility Rate', hue='Country Name', palette='tab20', legend=None)